/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.109
 * Generated at: 2025-12-03 12:01:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/components/navbar.jsp", Long.valueOf(1764757454694L));
    _jspx_dependants.put("/components/allcss.jsp", Long.valueOf(1764758175785L));
    _jspx_dependants.put("/components/footer.jsp", Long.valueOf(1764763213427L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Index Page</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("	\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-2SwdPD6INVrV/lHTZbO2nodKhrnDdJK9/kg2XD1r9uGqPo1cUbujc+IYdlYdEErWNu69gVcYgdxlmVmzTWnetw==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("	\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		integrity=\"sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".carousel-item img {\r\n");
      out.write("  height: 90vh;\r\n");
      out.write("  object-fit: cover;\r\n");
      out.write("  filter: brightness(70%);\r\n");
      out.write("  background-size:;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-caption h2 {\r\n");
      out.write("  font-size: 3rem;\r\n");
      out.write("  text-shadow: 0px 0px 10px #000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-caption p {\r\n");
      out.write("  font-size: 1.25rem;\r\n");
      out.write("  text-shadow: 0px 0px 10px #000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Our Services CSS */\r\n");
      out.write(".service-box {\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".service-icon {\r\n");
      out.write("  width: 50px;\r\n");
      out.write("  height: 50px;\r\n");
      out.write("  filter: brightness(0) saturate(100%) invert(55%) sepia(45%) saturate(500%)\r\n");
      out.write("          hue-rotate(120deg) brightness(95%) contrast(90%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*	Footer  */\r\n");
      out.write(".navbar {\r\n");
      out.write("  letter-spacing: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-link {\r\n");
      out.write("  font-size: 0.9rem;\r\n");
      out.write("  color: #ddd !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-link:hover {\r\n");
      out.write("  color: #00d4a7 !important; /* mint hover color */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".extra-links .nav-link {\r\n");
      out.write("  font-size: 0.8rem;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-success\">\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<a class=\"navbar-brand\" href=\"index.jsp\"><i class=\"fa-solid fa-hospital\"></i>MEDI HOME</a>\r\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("			data-bs-target=\"#navbarSupportedContent\"\r\n");
      out.write("			aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("			aria-label=\"Toggle navigation\">\r\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("		</button>\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("			<ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link active\"\r\n");
      out.write("					aria-current=\"page\" href=\"admin_login.jsp\"><i class=\"fa-solid fa-arrow-right-to-bracket\"></i>Admin</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link active\"\r\n");
      out.write("					aria-current=\"page\" href=\"doctor_login.jsp\"><i class=\"fa-solid fa-user-doctor\"></i>Doctor</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link active\"\r\n");
      out.write("					aria-current=\"page\" href=\"#\">Appointment</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link active\"\r\n");
      out.write("					aria-current=\"page\" href=\"user_login.jsp\"><i class=\"fa-solid fa-user\"></i>User</a></li>\r\n");
      out.write("\r\n");
      out.write("				<!--    <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Dropdown\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\r\n");
      out.write("            <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Carousel Start -->\r\n");
      out.write("<div id=\"hospitalCarousel\" class=\"carousel slide carousel-fade\" data-bs-ride=\"carousel\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Indicators -->\r\n");
      out.write("  <div class=\"carousel-indicators\">\r\n");
      out.write("    <button type=\"button\" data-bs-target=\"#hospitalCarousel\" data-bs-slide-to=\"0\" class=\"active\"></button>\r\n");
      out.write("    <button type=\"button\" data-bs-target=\"#hospitalCarousel\" data-bs-slide-to=\"1\"></button>\r\n");
      out.write("    <button type=\"button\" data-bs-target=\"#hospitalCarousel\" data-bs-slide-to=\"2\"></button>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Slides -->\r\n");
      out.write("  <div class=\"carousel-inner\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Slide 1 -->\r\n");
      out.write("    <div class=\"carousel-item active\">\r\n");
      out.write("      <img src=\"images/img05.jfif\"class=\"d-block w-100\" alt=\"Hospital\">\r\n");
      out.write("      <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("        <h2 class=\"fw-bold text-light\">Advanced Healthcare Services</h2>\r\n");
      out.write("        <p>Your health is our top priority.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Slide 2 -->\r\n");
      out.write("    <div class=\"carousel-item\">\r\n");
      out.write("      <img src=\"images/img06.jfif\" class=\"d-block w-100\" alt=\"Doctors\">\r\n");
      out.write("      <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("        <h2 class=\"fw-bold text-light\">Expert Doctors & Staff</h2>\r\n");
      out.write("        <p>Highly trained medical professionals at your service.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Slide 3 -->\r\n");
      out.write("    <div class=\"carousel-item\">\r\n");
      out.write("      <img src=\"images/img07.jfif\" class=\"d-block w-100\" alt=\"Medical Equipment\">\r\n");
      out.write("      <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("        <h2 class=\"fw-bold text-light\">Modern Medical Facilities</h2>\r\n");
      out.write("        <p>World-class technology for better treatment.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Controls -->\r\n");
      out.write("  <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#hospitalCarousel\" data-bs-slide=\"prev\">\r\n");
      out.write("    <span class=\"carousel-control-prev-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("\r\n");
      out.write("  <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#hospitalCarousel\" data-bs-slide=\"next\">\r\n");
      out.write("    <span class=\"carousel-control-next-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Carousel End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Our Services -->\r\n");
      out.write("<section class=\"py-5 bg-light\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Section Title -->\r\n");
      out.write("    <div class=\"text-center mb-5\">\r\n");
      out.write("      <h2 class=\"fw-bold\">Our Services</h2>\r\n");
      out.write("      <p class=\"text-muted\">TO CHOOSE FROM</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Services Grid -->\r\n");
      out.write("    <div class=\"row g-4\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Cardiology -->\r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <div class=\"service-box text-center\">\r\n");
      out.write("          <img src=\"icons/heart.svg\" class=\"service-icon mb-3\" alt=\"\">\r\n");
      out.write("          <i class=\"fa-regular fa-heart\"></i><h5 class=\"fw-bold\">Cardiology</h5>\r\n");
      out.write("          <p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lorem maximus malesuada.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Gastroenterology -->\r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <div class=\"service-box text-center\">\r\n");
      out.write("          <img src=\"icons/stomach.svg\" class=\"service-icon mb-3\" alt=\"\">\r\n");
      out.write("          <h5 class=\"fw-bold\">Gastroenterology</h5>\r\n");
      out.write("          <p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lorem maximus malesuada.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Medical Lab -->\r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <div class=\"service-box text-center\">\r\n");
      out.write("          <img src=\"icons/lab.svg\" class=\"service-icon mb-3\" alt=\"\">\r\n");
      out.write("          <h5 class=\"fw-bold\">Medical Lab</h5>\r\n");
      out.write("          <p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lorem maximus malesuada.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Dental Care -->\r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <div class=\"service-box text-center\">\r\n");
      out.write("          <img src=\"icons/tooth.svg\" class=\"service-icon mb-3\" alt=\"\">\r\n");
      out.write("          <h5 class=\"fw-bold\">Dental Care</h5>\r\n");
      out.write("          <p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lorem maximus malesuada.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Surgery -->\r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <div class=\"service-box text-center\">\r\n");
      out.write("          <img src=\"icons/surgery.svg\" class=\"service-icon mb-3\" alt=\"\">\r\n");
      out.write("          <h5 class=\"fw-bold\">Surgery</h5>\r\n");
      out.write("          <p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lorem maximus malesuada.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Neurology -->\r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <div class=\"service-box text-center\">\r\n");
      out.write("          <img src=\"icons/brain.svg\" class=\"service-icon mb-3\" alt=\"\">\r\n");
      out.write("          <h5 class=\"fw-bold\">Neurology</h5>\r\n");
      out.write("          <p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lorem maximus malesuada.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark py-2\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Brand (optional) -->\r\n");
      out.write("    <a class=\"navbar-brand fw-bold\" href=\"#\">HMS</a>\r\n");
      out.write("\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#mainNavbar\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"mainNavbar\">\r\n");
      out.write("\r\n");
      out.write("      <!-- LEFT MENU -->\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link mx-2\" href=\"#\">HOME</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link mx-2\" href=\"#\">ABOUT US</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link mx-2\" href=\"#\">SERVICES</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link mx-2\" href=\"#\">NEWS</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link mx-2\" href=\"#\">CONTACT</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <!-- CENTER EXTRA LINKS -->\r\n");
      out.write("      <ul class=\"navbar-nav mx-auto d-none d-lg-flex extra-links\">\r\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link small text-muted\" href=\"#\">Help Desk</a></li>\r\n");
      out.write("        <li class=\"nav-item px-2 text-muted\">|</li>\r\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link small text-muted\" href=\"#\">Emergency Services</a></li>\r\n");
      out.write("        <li class=\"nav-item px-2 text-muted\">|</li>\r\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link small text-muted\" href=\"#\">Appointment</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <!-- RIGHT CALL SECTION -->\r\n");
      out.write("      <div class=\"d-flex align-items-center\">\r\n");
      out.write("        <i class=\"bi bi-telephone-fill me-2 text-success\"></i>\r\n");
      out.write("        <span class=\"text-success fw-bold\">+34 586 778 8892</span>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
